package inventory.model;
// Generated Jun 30, 2020 3:20:38 AM by Hibernate Tools 5.4.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	private Integer id;
	private int parentId;
	private String url;
	private String name;
	private int orlderIndex;
	private int activeFlag;
	private Date createDAte;
	private Date updateDate;
	private Set auths = new HashSet(0);
	private List<Menu> child;
	private String idMenu;
	private Map<Integer,Integer> mapAuth;
	
	public String getIdMenu() {
		return idMenu;
	}

	public void setIdMenu(String idMenu) {
		this.idMenu = idMenu;
	}

	

	public List<Menu> getChild() {
		return child;
	}

	public void setChild(List<Menu> child) {
		this.child = child;
	}

	public Menu() {
	}

	public Menu(int parentId, String url, String name, int orlderIndex, int activeFlag, Date createDAte,
			Date updateDate) {
		this.parentId = parentId;
		this.url = url;
		this.name = name;
		this.orlderIndex = orlderIndex;
		this.activeFlag = activeFlag;
		this.createDAte = createDAte;
		this.updateDate = updateDate;
	}

	public Menu(int parentId, String url, String name, int orlderIndex, int activeFlag, Date createDAte,
			Date updateDate, Set auths) {
		this.parentId = parentId;
		this.url = url;
		this.name = name;
		this.orlderIndex = orlderIndex;
		this.activeFlag = activeFlag;
		this.createDAte = createDAte;
		this.updateDate = updateDate;
		this.auths = auths;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getOrlderIndex() {
		return this.orlderIndex;
	}

	public void setOrlderIndex(int orlderIndex) {
		this.orlderIndex = orlderIndex;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateDAte() {
		return this.createDAte;
	}

	public void setCreateDAte(Date createDAte) {
		this.createDAte = createDAte;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Set getAuths() {
		return this.auths;
	}

	public void setAuths(Set auths) {
		this.auths = auths;
	}

	public Map<Integer,Integer> getMapAuth() {
		return mapAuth;
	}

	public void setMapAuth(Map<Integer,Integer> mapAuth) {
		this.mapAuth = mapAuth;
	}

}
