package inventory.model;
// Generated Jun 30, 2020 3:20:38 AM by Hibernate Tools 5.4.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.web.multipart.MultipartFile;

/**
 * ProductInfo generated by hbm2java
 */
public class ProductInfo implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String code;
	private String name;
	private String description;
	private String imgUrl;
	private int activeFlag;
	private Date createDAte;
	private Date updateDate;
	private Set productInStocks = new HashSet(0);
	private Set histories = new HashSet(0);
	private Set invoices = new HashSet(0);
	private MultipartFile multipartFile;
	private Integer cateId;

	public ProductInfo() {
	}

	public ProductInfo(Category category, String code, String name, String imgUrl, int activeFlag, Date createDAte,
			Date updateDate) {
		this.category = category;
		this.code = code;
		this.name = name;
		this.imgUrl = imgUrl;
		this.activeFlag = activeFlag;
		this.createDAte = createDAte;
		this.updateDate = updateDate;
	}

	public MultipartFile getMultipartFile() {
		return multipartFile;
	}

	public void setMultipartFile(MultipartFile multipartFile) {
		this.multipartFile = multipartFile;
	}

	public Integer getCateId() {
		return cateId;
	}

	public void setCateId(Integer cateId) {
		this.cateId = cateId;
	}

	public ProductInfo(Category category, String code, String name, String description, String imgUrl, int activeFlag,
			Date createDAte, Date updateDate, Set productInStocks, Set histories, Set invoices) {
		this.category = category;
		this.code = code;
		this.name = name;
		this.description = description;
		this.imgUrl = imgUrl;
		this.activeFlag = activeFlag;
		this.createDAte = createDAte;
		this.updateDate = updateDate;
		this.productInStocks = productInStocks;
		this.histories = histories;
		this.invoices = invoices;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateDAte() {
		return this.createDAte;
	}

	public void setCreateDAte(Date createDAte) {
		this.createDAte = createDAte;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Set getProductInStocks() {
		return this.productInStocks;
	}

	public void setProductInStocks(Set productInStocks) {
		this.productInStocks = productInStocks;
	}

	public Set getHistories() {
		return this.histories;
	}

	public void setHistories(Set histories) {
		this.histories = histories;
	}

	public Set getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set invoices) {
		this.invoices = invoices;
	}

}
