package inventory.model;
// Generated Jun 30, 2020 3:20:38 AM by Hibernate Tools 5.4.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer id;
	private String roleName;
	private String description;
	private int activeFlag;
	private Date createDAte;
	private Date updateDate;
	private Set auths = new HashSet(0);
	private Set usersRoles = new HashSet(0);
	

	public Role() {
	}

	public Role(String roleName, String description, int activeFlag, Date createDAte, Date updateDate) {
		this.roleName = roleName;
		this.description = description;
		this.activeFlag = activeFlag;
		this.createDAte = createDAte;
		this.updateDate = updateDate;
	}

	public Role(String roleName, String description, int activeFlag, Date createDAte, Date updateDate, Set auths,
			Set usersRoles) {
		this.roleName = roleName;
		this.description = description;
		this.activeFlag = activeFlag;
		this.createDAte = createDAte;
		this.updateDate = updateDate;
		this.auths = auths;
		this.usersRoles = usersRoles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateDAte() {
		return this.createDAte;
	}

	public void setCreateDAte(Date createDAte) {
		this.createDAte = createDAte;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Set getAuths() {
		return this.auths;
	}

	public void setAuths(Set auths) {
		this.auths = auths;
	}

	public Set getUsersRoles() {
		return this.usersRoles;
	}

	public void setUsersRoles(Set usersRoles) {
		this.usersRoles = usersRoles;
	}



}
