package inventory.model;
// Generated Jun 30, 2020 3:20:38 AM by Hibernate Tools 5.4.3.Final

import java.util.Date;

/**
 * UsersRole generated by hbm2java
 */
public class UsersRole implements java.io.Serializable {

	private Integer id;
	private Role role;
	private Users users;
	private int activeFlag;
	private Date createDAte;
	private Date updateDate;

	public UsersRole() {
	}

	public UsersRole(Role role, Users users, int activeFlag, Date createDAte, Date updateDate) {
		this.role = role;
		this.users = users;
		this.activeFlag = activeFlag;
		this.createDAte = createDAte;
		this.updateDate = updateDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateDAte() {
		return this.createDAte;
	}

	public void setCreateDAte(Date createDAte) {
		this.createDAte = createDAte;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
